apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: toi
  name: rekrutteringsbistand-kandidat-bigquery
  namespace: toi
spec:
  image: {{ image }}
  schedule: "0 0 1 * * ?"
  webproxy: true
  vault:
    enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 8000Mi
    requests:
      cpu: 1000m
      memory: 4000Mi
  env:
    - name: APPLICATION_NAME
      value: rekrutteringsbistand-kandidat-bigquery
    - name: VKS_VAULT_ADDR 
      value: https://vault.adeo.no
    - name: VKS_AUTH_PATH
      value: auth/kubernetes/prod/fss/login
    - name: VKS_KV_PATH
      value: kv/prod/fss
    - name: VKS_SECRET_DEST_PATH
      value: /var/run/secrets/nais.io/vault
    - name: K8S_SERVICEACCOUNT_PATH
      value: /var/run/secrets/kubernetes.io/serviceaccount
