apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: toi
  name: rekrutteringsbistand-kandidat-bigquery
  namespace: toi
spec:
  image: {{ image }}
  schedule: "*/1 * * * *"
  vault:
    enabled: true
  env:
    - name: K8S_SERVICEACCOUNT_PATH
      value: /var/run/secrets/kubernetes.io/serviceaccount